### PR TITLE
[DNM] [r-mr1] hal: Add support for sm8150+sdxprairies

### PR DESCRIPTION
**Pull request by pablomh**
This commit makes voice audio work on `pioneer` (at least).

It needs testing in the rest of the supported plaforms (I'll be testing in `seine` in a bit).

-----

Make hal layer changes to support for hanasdx55 target.

Change-Id: Id2c7cbfe2a879c5de7b0260fa9895e4606a805b0
Signed-off-by: Pallavi Mishra <pallavim@codeaurora.org>

### CODE REVIEW

**Comment by pablomh** [comment]
This commit was in `q-mr1` as well.

**Comment by MarijnS95** [comment]
@pablomh Can you revert this commit locally and instead disable [the definition of `PLATFORM_AUTO`](https://github.com/sonyxperiadev/vendor-qcom-opensource-audio-hal-primary-hal/blob/8385c2b88cddf7c22ee74ace4227e65b76567d43/hal/Android.mk#L120-L122) that we talked about last time?

That is the only difference this commit is making to Nile platforms.

**Comment by MarijnS95** [comment]
Also means the previous commit/PR to define `HOST_LESS` pcm ids was not necessary if we disable AUTO. In the end I prefer as little picked commits as possible, they likely didn't make it into 9.11 tags for a reason.

**Comment by pablomh** [comment]
Will try the following and will get back with the results:

```diff
diff --git a/hal/Android.mk b/hal/Android.mk
index a56a45cf..be8ec9ce 100644
--- a/hal/Android.mk
+++ b/hal/Android.mk
@@ -117,10 +117,6 @@ ifneq ($(filter msm8953,$(TARGET_BOARD_PLATFORM)),)
 endif
 endif

-ifeq ($(TARGET_BOARD_AUTO),true)
-  LOCAL_CFLAGS += -DPLATFORM_AUTO
-endif
-
 LOCAL_CFLAGS += -Wno-macro-redefined

 LOCAL_HEADER_LIBRARIES := libhardware_headers
diff --git a/hal/audio_extn/Android.mk b/hal/audio_extn/Android.mk
index 31159af1..b3823b8e 100644
--- a/hal/audio_extn/Android.mk
+++ b/hal/audio_extn/Android.mk
@@ -536,10 +536,6 @@ ifneq ($(filter sdm845 sdm710 sdmshrike sm8150 kona lahaina holi lito bengal ato
   MULTIPLE_HW_VARIANTS_ENABLED := true
 endif

-ifeq ($(TARGET_BOARD_AUTO),true)
-  LOCAL_CFLAGS += -DPLATFORM_AUTO
-endif
-
 LOCAL_SRC_FILES:= \
         hfp.c \
         device_utils.c
```

**Comment by pablomh** [comment]
After testing the previous diff I've got audio working on both `seine` and `nile` and even got the headphones routing working on `seine` (which didn't work for me).

Should I close this and submit a new PR with the revert and the proposed change disabling `TARGET_BOARD_AUTO` or should we ask @jerpelea to reset the tree to https://github.com/sonyxperiadev/vendor-qcom-opensource-audio-hal-primary-hal/commit/b966d2bbd3961ef339c2811cc2cece5de18e473f?

**Comment by pablomh** [comment]
Discarding this in favor of https://github.com/sonyxperiadev/vendor-qcom-opensource-audio-hal-primary-hal/pull/13.

**Pull request closed without merging**
