### PR TITLE
Android.mk: Change kona to $(KONA)

### PR DESCRIPTION
**Pull request by Haxk20**
As far as i know we want audio on Kona devices (Edo platform) so lets change kona to $(KONA) so
those devices will build this HAL.

KONA is defined in edo device tree.

### CODE REVIEW

**Comment by Haxk20** [comment]
Just checked and there are way more kona references. I will update the PR once all of them are taken care of

**Comment by MarijnS95** [comment]
@Haxk20 Before that, might we want to check other tags? Btw, you're submitting this against `q-mr1`, but Edo is probably only going to be brought up on `r-mr1` (which we based on `LA.UM.9.11.r1-02100-NICOBAR.0` 4 months ago, FYI).

**Comment by Haxk20** [comment]
> @Haxk20 Before that, might we want to check other tags? Btw, you're submitting this against `q-mr1`, but Edo is probably only going to be brought up on `r-mr1` (which we based on `LA.UM.9.11.r1-02100-NICOBAR.0` 4 months ago, FYI).

Indeed. I will rebase it on r-mr1.
Ty marijn <3

**Comment by Haxk20** [comment]
All references to kona for platform usage have been replaced with $(KONA).

Please somebody review this if i didnt make mistake somewhere.

**Pull request merged**
